# Generated by Django 4.2.1 on 2023-06-03 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('hostname', models.CharField(max_length=2048, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('url', models.CharField(max_length=2048, primary_key=True, serialize=False)),
                ('title', models.CharField(default='No Title', max_length=64)),
                ('host_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='history_handler.host')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='history_handler.url')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history_handler.user')),
            ],
        ),
    ]
